### PR TITLE
Start using bloscpack for the text serialization too.

### PR DESCRIPTION
**Pull request by esc**
Still needs to be benchmarked for speed and memory performance. Also the
blosc_args can probably be tweaked.

### CODE REVIEW

**Comment by esc** [comment]
And eventually support for object arrays should probably move to bloscpack itself.

**Comment by esc** [comment]
@mrocklin @jcrist do you have a benchmark handy for profiling text data storage with castra?

**Comment by mrocklin** [comment]
I have historically used actual datasets for this; I don't have anything artificial.  @jcrist  was recently working on the reddit data dumps.  He might have something interesting to work with (if you're willing to download a bit of data.)

**Comment by jcrist** [comment]
The reddit data provides a pretty good benchmark, a wide variety of string data.

[This script](https://gist.github.com/jcrist/fce59a8afd89d2e20015) will convert the comment data from [here](https://mega.nz/#!ysBWXRqK!yPXLr25PgJi184pbJU3GtnqUY4wG7YvuPpxJjEmnb9A) into a castra. The `body` column is composed of ~55 million strings of varying lengths.

**Comment by esc** [comment]
I am closing this as I won't have time to finish it for now. Perhaps another time.

**Pull request closed without merging**
