### PR TITLE
escape directory names

### LINKED ISSUE #41: "." columns
I read your post ["Efficient Tabular Storage"] (http://matthewrocklin.com/blog/work/2015/08/28/Storage/)  and decided to to give Castra a whirl.  As my luck would have it, I got an error on the very first data set I tried.

The problem is that the dataframe has a column that is labeled "." (period, without quotes) and, of course, on *nix this is an invalid name for regular files.  I don't know if/how you would want to fix this.  I've written a test case nontheless.

    def test_column_with_period():                                                                      
        df = pd.DataFrame({'x': [10, 20],                                                               
                           '.': [10., 20.]},                                                            
                          columns=['x', '.'],                                                           
                          index=[10, 20])                                                               
                                                                                                        
        with Castra(template=df) as c:                                                                  
            c.extend(df) 

Which yields:

    >       with open(filename, 'wb') as fp:
    E       IOError: [Errno 21] Is a directory: '/tmp/castra-uUz3Gr/10--20/.'

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes #41  cc @enku

### CODE REVIEW

**Comment by mrocklin** [comment]
This could be improved with a more rigorous system to escape names for the file system.  Does anyone know of a common solution here?

**Comment by jcrist** [comment]
One of my potential improvement plans was to remap the names to an iteration (something like `part_1`). Since we have the partitions stored in meta, then the partitions series is just `pd.Series(sorted(glob('part_*')), index=partitions)`. Simple, consistent (and valid) filenames.

**Comment by jcrist** [comment]
Woops, just realized this is a problem with columns, not the index. [This stackoverflow](http://stackoverflow.com/questions/295135/turn-a-string-into-a-valid-filename-in-python) has some ideas, but they're all pretty shaky. I'm not sure if there is a rigorous way to do this cross-platform.

**Comment by mrocklin** [comment]
Eventually I'd like to remove separate partition files all-together and have just one file per column with an index of byte locations.  I suspect that this would improve large read times.

**Comment by mrocklin** [comment]
I'm now using a whitelist and hashing.  Merging soon if no comment.

**Pull request merged**
